# pre-req is to create a source table/view that contains std. fields. see input below
# note that emails, phones should be split into rows with corresponding personal information
  # e.g. VAN profile with two phone numbers will lead to two rows here
  # how best to link chapters? "VAN Employer Name 1:1 match with UW? How about bargaining units?" - some spelling is different

linkages:
  - name: member_job
    version: 0.1 # update version to reprocess all with new params
    input:
      schema: input_schema
      table: input_table
    entities:
      - name: job
        output_id: job_id
        training_file: file_location.json
        variable_blocks: # only compare records with matching blocked variable (if present)
          - field: chapter # chapter from previous linkage
          - field: uw_job_id
            has missing: True
        variable_definitions: # YML version of settings for dedupe.io https://docs.dedupe.io/en/latest/Variable-definition.html
          - field: uw_person_id
            type: Exact
          - field: first_name
            type: String
          - field: last_name
            type: String
          - field: hire_date
            type: DateTime
            has missing: True
          - field: birth_date
            type: DateTime
            has missing: True
          - field: employee_id
            type: Exact
            has missing: True
          - field: card_sign_date
            type: DateTime
            has missing: True
          - field: zip_code
            type: Exact
            has missing: True
          - field: street_address
            type: String
            has missing: True
          - field: phone # IF DUPLICATES 1 PER ROW
            type: Exact
            has missing: True
          - field: email # IF DUPLICATES 1 PER ROW
            type: Exact
            has missing: True
          - field: department
            type: string
            has missing: True
          - field: work_area # same as department on cards
            type: string
            has missing: True
          - field: job_title
            type: string
            has missing: True
      - name: person
        output_id: person_id
        variable_blocks: # only compare records with matching blocked variable (if present)
          - field: uw_person_id
            has missing: True
          - field: uw_job_id
            has missing: True
        variable_definitions: # YML version of settings for dedupe.io https://docs.dedupe.io/en/latest/Variable-definition.html
          - field: uw_person_id
            type: Exact
          - field: uw_job_id
            type: Exact
          - field: first_name
            type: String
          - field: last_name
            type: String
          - field: birth_date
            type: DateTime
            has missing: True
  - name: chapter # name is for organizing, not used
    version: 0.1
    active: false
    input:
      schema: input_schema
      table: input_table
    entities:
      - name: chapter
        output_id: chapter_id


## BRAINSTORMING BELOW

# add to input schema to specify columns for parsing
      columns:
        - name: full_name
          - parse: name
        - name: address_full
          - parse: address



